### ISSUE TITLE
Hard to understand crashes if target devices sends empty/incomplete data

### ISSUE THREAD

**Issue by ntninja** [Jc2k/aiohomekit#11]
I just thought I'd document this: When the target device sends a supposedly incomplete or empty response (as in the first patch of #9 in my case), aiohomekit will crash with an assertion error. There are two problems with this:

   * Assertions are debug-only: When running Python in optimized mode (`python -O …`), the assertions will disappear and aiohomekit will happily continue operations with invalid data.
   * The statemachines in `aiohomekit/protocol/__init__.py` each return a list of “expected” OP codes that does NOT do what I, at least, expected: When reading this code, I assumed this would cause the caller to ensure that the provided TLV values contain *any* of the *expected* items in the order given in that list – the reality [is a bit different](https://github.com/Jc2k/aiohomekit/blob/5d818696c563d70199da1896b686620ab3478dec/aiohomekit/protocol/tlv.py#L102-L126) and I'd be very interested in any explanation as to what the actual code is supposed to achieve. :slightly_smiling_face:

**Comment by Jc2k** [comment]
* Any asserts are carried over from homekit_python and haven't been refactored away yet, or they got left in by accident when debugging
* Most of the TLV code is from homekit_python too, e.g. https://github.com/jlusiardi/homekit_python/blob/0.15.0/homekit/protocol/tlv.py#L99. The TLV code has changed on master but i haven't reviewed the changes or tried to import the changes yet. I'm afraid I can offer you no further insight.

I'm not a fan of the "expected" either, and I don't like that it returns a list of (k, v). Would much rather have at least a dict. But ideally a proper type.

The IndexError on empty body is also really annoying, even though an empty body is off spec it is frustratingly common for HAP implementations to return a 400 with no error TLV body.

**Comment by Jc2k** [comment]
One thing I do remember from conversations with the original author is that both the order of the TLV entries is not stable and that some devices are sensitive to it not being stable. E.g.

* https://github.com/jlusiardi/homekit_python/pull/36
* https://github.com/jlusiardi/homekit_python/pull/96

So it looks like a rudimentary sort is done to alleviate that?

The "my approach" alluded to in PR 96 was writing the code to not depend on the ordering (using expected as a validation aid only) and return a dict or something. This would make the secure session setup code a lot nicer.

**Comment by Jc2k** [comment]
As I can't give you the insight you are looking for, and this ticket isn't really directly actionable, i'm going to close it favour of #13 (low priority but nice TLV parsing cleanup) and #14 (more priority, throwing some useful errors). Feel free to raise more cleanup ideas! Can't promise when anyone will get to them though..
