### ISSUE TITLE
Migrate to cryptography > 3

### ISSUE THREAD

**Issue by fabaff** [Jc2k/aiohomekit#21]
[cryptography 3.x](https://cryptography.io/en/latest/changelog/) was release a while ago. It would be nice if aiohomekit is migrated to cryptography to allow the installation along other modules in the same `venv`.

Fedora's development release already ships cryptography 3.x.

**Comment by Jc2k** [comment]
`main` now uses a >= pin for that dependency which should work, but should still be compatible with home-assistant (which is also on 2.9.x like aiohomekit). Let me know if that works for you and i'll push out a release.

**Comment by fabaff** [comment]
Thanks for the change.

Was fixed with https://github.com/Jc2k/aiohomekit/commit/f29f54b662fd32c4b63a305f533a2411601e1ab1
