### ISSUE TITLE
Save the last broadcast key between runs

### ISSUE THREAD

**Issue by bdraco** [Jc2k/aiohomekit#215]
The wemo stage seems to not accept connections as frequently anymore once broadcast events have been subscribed to

**Comment by bdraco** [comment]
`Oct 28 22:45:02 homeassistant homeassistant[491]: 2022-10-28 17:45:02.146 DEBUG (MainThread) [aiohomekit.controller.ble.pairing] Onvis-SMS1-3b2d1a [CD:A3:FA:D1:50:56] (id=82:09:82:0E:65:E0): Received notification before session is setup, falling back processing as disconnected event: HomeKitEncryptedNotification(name='Onvis-SMS1-3b2d1a', address='CD:A3:FA:D1:50:56', id='82:09:82:0e:65:e0', advertising_identifier=b'\x82\t\x82\x0ee\xe0', encrypted_payload=b'`\x8cz\x96D-\x95\xab}Ed}>+\x054')`

The key would be the same since last time if we had saved it

**Comment by bdraco** [comment]
Not really sure where to put the key to save it between runs

**Comment by Jc2k** [comment]
If it's effectively mandatory for some devices does it really belong on the config entry?

**Comment by bdraco** [comment]
We refresh it every time we connect so I'm not sure it would be good to write it to the config entry.  Probably better to put it in the entity map file since we churn that a lot more?

**Comment by Jc2k** [comment]
Maybe. Up until now that has just been cache (you could rm it). But that not set in stone.

**Comment by bdraco** [comment]
I think it’s ok to rm it as we can get a new one it will just take a few tries to connect

**Comment by Jc2k** [comment]
I am sold 👍
