### ISSUE TITLE
dependency on unmaintained commentjson

### ISSUE THREAD

**Issue by stanislavlevin** [Jc2k/aiohomekit#380]
`commentjson` is not updated over 4 years:
https://pypi.org/project/commentjson/

and repo looks unmaintained:
https://github.com/vaidik/commentjson/

**Comment by Jc2k** [comment]
If there is a bug or compatibility issue reported and upstream is non-responsive then we'd normally fork it (if a suitable replacement is not readily available). At the moment no one has reported any bugs or compatibility issues, tho, so there is nothing we'd do right now. If you are aware of any such problems, please do file issues for them.
