### ISSUE TITLE
aiocoap: Wait for release

### ISSUE THREAD

**Issue by Jc2k** [Jc2k/aiohomekit#68]
We want the following:

* https://github.com/chrysn/aiocoap/pull/270/files
* https://github.com/chrysn/aiocoap/issues/271

**Comment by Jc2k** [comment]
@roysjosh As it looks like maintainer is unresponsive, we should probably start looking at alternatives.

I'm curious to see if my -3000 idea works. Maybe we can reach out to pytradfri for the other issue. It's a HA project so i expect they'll be much more responsive.

I am tempted to call out the incompatibility in the docs, link to bugs, wash our hands of it, though we probably shouldn't.

I'd prefer not to fork when the maintainer is still actively committing. But maybe they are not happy with Home Assistant using aiocoap and would rather we go away. What can we do if so.

**Comment by chrysn** [comment]
Apologies, I've just lost track of the criticality of the issues; feel free to poke me when I don't get things unblocked.

**Comment by Jc2k** [comment]
Thanks for the quick response. Really appreciate the work you do on aiocoap. Excited to turn on homekit coap support in HA very soon :)
